"""empty message

Revision ID: 03beff0a0f80
Revises: f3586d1cb8d2
Create Date: 2020-12-18 00:27:59.783218

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '03beff0a0f80'
down_revision = 'f3586d1cb8d2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('admin')
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('has_admin_previlages', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('has_admin_previlages')

    op.create_table('admin',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('admin_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['admin_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
