"""test

Revision ID: 0a1005e567ac
Revises: 41651e45b573
Create Date: 2020-12-16 10:32:04.727908

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0a1005e567ac'
down_revision = '41651e45b573'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('has_unseen_messages')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('has_unseen_messages', sa.BOOLEAN(), server_default=sa.text("'f'"), nullable=True))

    # ### end Alembic commands ###
