"""followers

Revision ID: 19061939c686
Revises: ef7c34e2e7b2
Create Date: 2020-12-06 21:43:40.926199

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '19061939c686'
down_revision = 'ef7c34e2e7b2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('followers',
    sa.Column('follower_id', sa.Integer(), nullable=True),
    sa.Column('followed_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['followed_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['follower_id'], ['user.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('followers')
    # ### end Alembic commands ###
