"""test

Revision ID: 26542031f86a
Revises: 0a1005e567ac
Create Date: 2020-12-16 10:33:04.684732

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '26542031f86a'
down_revision = '0a1005e567ac'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('has_unseen_messages', sa.Boolean(), server_default=sa.text('0'), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('has_unseen_messages')

    # ### end Alembic commands ###
