"""removed nullable

Revision ID: 41651e45b573
Revises: 619a1b90d98f
Create Date: 2020-12-16 10:29:06.736074

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '41651e45b573'
down_revision = '619a1b90d98f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('has_unseen_messages',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text("'f'"))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('has_unseen_messages',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text("'f'"))

    # ### end Alembic commands ###
