"""Unseen Messages

Revision ID: 619a1b90d98f
Revises: 34caaff7462a
Create Date: 2020-12-16 10:26:35.449503

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '619a1b90d98f'
down_revision = '34caaff7462a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('has_unseen_messages',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text("'f'"))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('has_unseen_messages',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text("'f'"))

    # ### end Alembic commands ###
