"""empty message

Revision ID: a193ac052197
Revises: da3557ddebb4
Create Date: 2020-12-15 08:16:59.090219

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a193ac052197'
down_revision = 'da3557ddebb4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('message', sa.Column('seen_time', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('message', 'seen_time')
    # ### end Alembic commands ###
