"""Message Migration2

Revision ID: f1b6488d0eae
Revises: 5a9268d7052b
Create Date: 2020-12-14 23:31:25.264816

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f1b6488d0eae'
down_revision = '5a9268d7052b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('message', sa.Column('recipient_id', sa.Integer(), nullable=False))
    op.drop_constraint(None, 'message', type_='foreignkey')
    op.create_foreign_key(None, 'message', 'user', ['recipient_id'], ['id'])
    op.drop_column('message', 'receiver_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('message', sa.Column('receiver_id', sa.INTEGER(), nullable=False))
    op.drop_constraint(None, 'message', type_='foreignkey')
    op.create_foreign_key(None, 'message', 'user', ['receiver_id'], ['id'])
    op.drop_column('message', 'recipient_id')
    # ### end Alembic commands ###
